language: cpp
compiler: g++
os: linux
arch: arm64
env:
  global:
    secure: MAfDMh3exErb3morls10d+05li37cJ9ds5auwZoHExi0s9CnMoE9dYmWyJGZWUv0I0bnu9vClNXKdyEEaFzghjBK5p7E//z6DAdBvfiHNQEViT7EmHFt+PGrduYvUcs3srMaaxJDy4yit0+uRIcTgxP8Lvyld1vwOaRZh0yKkn9wXcM+ZtpdXFTfhGtc7QuSm+XTyNXk4ISbjdfC5d1pZ/F46g3wKl4EacfWVjwVwZQePrz407pze7uv0YY/quavbUlplns7up4i1f+/F2CCIzOOZ/uozDgedPILi3OQoYBfCLSYMgP2zu3baLiTTSengPKdE5kPeF5C+4DGQRDS8Q7Hnw4b+Oytygtfde0e0Ni6BSHMvU8gKpu5oT5minKHOFBYFoM9T10uijVuFw0U2Pri1qEVfllBFyknXyUgYKN5iy6wcAfxFuDciNkHfrpD/7Cg0rHZ5T4o6C+K1Sw/373z4EAEyTRf+3TuTt4n4Y0NwLIiS+kK8qvB0SzO4km3xnaX+kYBn/GU6j1yN0jMjzwbRglg1WAmV6cFFmNBlU3yu6G2pOyVvKZ8jyrqfDLtH4F7X8W2zieb6uowoctgm8JCpbhn4cKBDzCou/LKAEmg046IhKG0GzXo9u3pKd/KTuSx6q+Xs691rLCFHqvMbevk6eBpE8oHtLUTvzA5y64=
addons:
  coverity_scan:
    project:
      name: Lnossa/testCI
      description: Test CI
    notification_email: liviunossa@gmail.com
    build_command: chmod ugo+x build.sh && ./build.sh
    branch_pattern: master
script: chmod ugo+x build.sh && ./build.sh
