on: push
language: cpp
compiler: g++
os: linux
arch: arm64

#**************COVERITY BEGIN**************

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
- secure: "ndoqUSsizTlLqaoS+PVVripLmr5iiupQhnpHqUrkamxvdcqxMMB6V3oj3BSIeMae7WP/D6oXA00SZHZBP1iG/li4FNViTAh324HC57CeCnTYtPkNXVYgLRjf2CzbG6zDo8PPLo4UVMjN/TtkBckE6itIdmUe/fo6c0RByuKDh9ZqaS0Jr4JzCQqG4L3Vo2EeaE4l5bczK9zVgqTg2nDmBdmxPkbYO57zwPUDdcLRwCVRIQJ4BREwv4rwrz09I0R21O7BVRPqC32GwfaEPf5L9hKvP8GaQb9tuoSEw1h70CMhc+TWfVPqMtNeiyn+fPxU5pTwEEq9l2Ozpd7GvTdUAItiAcvaEc38u2CA4zKhW+d1Id0hI6sSsIjxNNDWBMIB/0J7TJijn3OSTSMzyLgHaB23LE0YjypmAlokAIp6uccK5wOO+wZYjKpjeUWn4rfqOIRq5Y+nAkxfJbLNaDp7kWOH7/jWa7qTeiITV4Mu4j89qCcPUyXbxJyfwkDfQbVU5QWqc2xKIF/Ud0orJn1qL3WtNAvU3mAZkk2rRhH9sbpH6Lt681YAg+7xyn1dKs7FQ3a1xyYBVR5uECVNfqXdosYJ6fbZnhBcQ5kviHRdHzRBCJHEDubJeBN3+84fDvDo3qr2mYquVAwlSxqhkyBKe9QsIiofawtXBmfHsAIBrLA="
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Lnossa/testCI"
      description: "Test CI"
    notification_email: liviunossa@gmail.com
    build_command: "chmod ugo+x build.sh && ./build.sh"
    branch_pattern: master

#**************COVERITY END**************

script: chmod ugo+x build.sh && ./build.sh