language: cpp
compiler: g++
os: linux
arch: arm64
env:
  global:
  - secure: cKUOGNDUP6Q/A+isz/VPg8vU43cM/4ybNycxOmdJMiy8RSEUU6ZMQp+p5ursFDUj9RNqW9mYzcWU7f46h29aTIq9cp6t3AMBkC+vt/98KlAbEu6PYlGtmQaOdkDuhS7Ax2Xu6bELMABgvv/0Gwa7M9dMWtXTY9x1Ub4iVGaPQJmKJnnFiHjLHuLhal83FeOAPRXjB2th2r7Fzc/IBu4pPx0pDj0P9kSqCsTDzus9Yj/xKGlP+irPckYRf6V+uXN5pMG3tFYAUMVHiAxVOGG2jsaBaQmfo16TyQc2OvUlypOCAeIdZaWWpK81w3M7zqbDkKagbQF+fnesvixdyG8mTREAaxbe0MlQsYT1xTx5LqU86QcfVFqWN1Y6WI159el7ShOMhpxyh095ipj7AbYD3uiOm1B/RJmT+JHfM0j+z2IJpubNbUn5Ok6U6N7IA1n1/YD+XPx2MLYtdgKkAOSRmCUeh7qeHXGCf3e50eHFqhAowkZw/31+9kFKmckPttd62U3espoa5T00EtDdM7P3MlaNLUEtpfQTN7tQEPu2prrYdsGAbXK7y7apO7yvmqSf8+IQFpBIqfdQVdQxhXLbQkV6h85Q49NDaqMZN5mKlZDZf6Inap/EKTigwkmxjbdtZzdEKhLvGT7DL148mjo71fD0CawkoiEg34Mbmn2owSw=
  - secure: Si4RR2nM9Zyy6Af1J64EqFAis5IpHCVZFPLr+v9mJ52vx77rqgW4/nYYoJ2OQ0w2Q/KI2PbH6UDrwS9SCdRxnUsVzZO2mqAEORgoNhAVvyuslvmFF6XjSbAMLLPBpOP9D2JtOvkRGnCWj7Qdbq+Y3N+nvTaYlM9fwTx0KMlEVCgHmF3YW30UO25wjEx8IpJuxoK8//lPPoFL7v9MG/GrSC0KisrVoOIspL2MYV7JN+Us96E7jIbhE1vRHE+7Qb8iSG10pFr5pWiRbtpn3IHJteUejybthppi7FY0aDsRyIFCf0Z4wTj0hHfRno1xgrZSn94lj5XESb53z1ELP4R8yOk0bW+xPUj/So9OKtfNEpjuRDu+AYuiXGd1Ob7ZFTIY0ewYeELcewUs18sWrL49YHYIUnEaLDc8Y0nUqik1saKT+kJU17pcuQ+6iY4WkqfBCYd+pdmFI4qUNLCBFSXVZBjw6d1moP8J4nK7VyuqoI8mLHP/5wa4YhnJK0/g4xUBh/ZOZjTOUc3YdU2peDBTBW6QKbdD8j6vp5IGYPlfDUk3atW49QM2bszhqcAC24WyZtHT/jQpCB4DKs9xpHl3xGml9Pq4Nq5GDr5YBNRix+PwHLnZbLPHjTd05CiuEyWNjStCrsQ8jmy0LtPITeXUF8cta/QyM0sPsu7TeIWucU4=
addons:
  coverity_scan:
    project:
      name: Lnossa/testCI
      description: Test CI
    notification_email: liviunossa@gmail.com
    build_command: chmod ugo+x build.sh && ./build.sh
    branch_pattern: master
script: chmod ugo+x build.sh && ./build.sh
