on: push
language: cpp
compiler: g++
os: linux
arch: arm64

#**************COVERITY BEGIN**************

env:
  global:
   - secure: "duYLSkoZHCjj9vKYC2ijKK78m6uGp6tZm+WnW3hPzOFN9YbJTLVGFVQwl8FIBMfhYLNugeUAaMjO++EbSIfBInUhistIvlAtvD5kZDqLxH3VU07w2hDPVjq/nBggYKO96E27scQvzKRtf9TSkyT0nSNeBDyYD/pLa6x8wMn+K/EyNXfZpthpyM2Q1h11TtIPZ2liYRdh3CC7bAOMqnRFnoHInhv/yWXeufNU4/cBgtc9auwW9Xtm8mQyaAcydHUNP4MLofkqbq65jpYYko246BBmO9BLFrqEeiM94jNUD76321MQ290mhfTK08Xe17HJXlg0EbHIyrkCr/PdVTrBioI+/zMhK3NKHoIyaQtFpaoo6sXQUPJjIQ1dKTVmUY99F07LLi/w1e5Qp7e/V+Cra6TrkF5BcDDWaxdfAh/PogLglYpUHfB1pp0PCERRz8tErcJ3QXFB7pkFlzE1udE38OKXj2RZL02Gz8Z7YUVKkjTTCX245rUOlV643nH6a/uFLzC93N2/KT6s5Y4xcDzI5YKeIH+iPO9ylBS5HJcHHm/AzKS09pwRS6p6IgHJbG6hJnUK5932WbHKFhBJzVK55Z40kYqlwOT+cJjjJ3H7OVvngEnbog2CBHOTY96Pb2qnpHVFiwmU30TF9Pv43ijadNAo4ozwLs7rvtmpECMgcMw="
  
  addons:
  coverity_scan:
    project:
      name: "Lnossa/testCI"
      description: "Test CI"
    notification_email: liviunossa@gmail.com
    build_command: "chmod ugo+x build.sh && ./build.sh"
    branch_pattern: master

#**************COVERITY END**************

script: chmod ugo+x build.sh && ./build.sh