on: push
language: cpp
compiler: g++
os: linux
arch: arm64

#**************COVERITY BEGIN**************

env:
  global:
   - secure: "awrDx65vit+SH4lEHU0j4aSIwmGVhHo2GZecJTf2MGJdmXiEfHCxmXqjfS0eZ33saQcSncjwMifrWjZM84IZ0rf/toXnTmHGi64U/sNTijyIaoRpGFlgfTU/Y8un+XqTNnZ38nacTb8/fFg9A0ql8lZ7WZiJS1dwonf3XpTtH5xX0xKd8y04/ZMFjORld5mYCdaSw/4fATmMgKFRNsSJPyrHV82XYwqyvxYYvjdygMp9y+UtFL1FZrA2+4HhJmWjt1sO5W6Cy+/94Yke1UFIfq+pYf1ZBT54fH/HdEsjdC/RjjhJ5H6zf8uVRa8ObNTGPnLC2U5yXYUJsLpFF/GI1WoJ5m6I8AGoDxkpBrfZtgLMsCYp8jJ/UvENYrwmFT41HgphtKgoGWEnIl+7o13fXXYnnZ2BTGzQQW3W1+ulYQo4jbZ5n08lajTo14R5VlolgTuzfT1NcyQq8dbbu0IqbI1qxYJdd6DVmpnzCXLysBBKR8/siQnmVQTNq2lipQeaStCNB/ow9mUCe/D3pufK2U16sV9F++rus392XHpbnvdUkjEed4GxVnPHE6axeua//MsDcWR+gmD9Uffm5pJT3eUtVC3HSNZB9dCWZxeOj5tzQkwGdrpQ66nCn5TPtoVfMPDGk2b/EsRhgDA1Tq3a4R7UJLJkuC7IAU8uE1mou5Y="
addons:
  coverity_scan:
    project:
      name: "Lnossa/testCI"
      description: "Test CI"
    notification_email: liviunossa@gmail.com
    build_command: "chmod ugo+x build.sh && ./build.sh"
    branch_pattern: master

#**************COVERITY END**************

script: chmod ugo+x build.sh && ./build.sh