on: push
language: cpp
compiler: g++
os: linux
arch: arm64

#**************COVERITY BEGIN**************

env:
  global:
    - secure: "AcByc7M4CoCtrHGeRVaC2mrUSkLH31SXrowUrUqX/hLvwzpWcJfZabYboXcwJYUG7Pt0jDNgnduE3zTnL8kO5R8tvwistldFqC8SfCkOnjPhba1ilZolMyGLgQaS3fFY6vQRqwR4MGCAtIVS68FLl2MI2QbBMWS8IF94DV/YowN2rTtPY9O+L+yRxFMoK91T9Zql4IO14vXWZIn4EctfXvKXdUkYPItwIe0pClCKqiADd91jUz8g4T/s6YU32hLPDu5uTO/fwvCumogFNhyueR++ILzG+egfxK5Ud3VAOYzH6Zzr3EbnHCzpHOA4Ds/ypntBJzhFfo2aQKGco3K+AaiEml1IA3gtME1G0++TkaGFABa3AUO5wWqz3/Rf6armcfPFnPWUSyVocOPue2nD9WtJG/xibKi6wUMAfAXjtEBaxhxhKle7ottuxExC7ms21HVSFLB2+EyXG0VMwDF0FdIithh0nwf4+ieXq2fQatKAuwOmFOIjRk7o4mOUvwPynXv74+A2hm2ArnFTI1/2BUAsqCzlpSQYDo3SYi+Zo+lJfdwCvDVsjJ1KTZVfWxKSGpZ2K2elAKi+OERpVa46gQbqn2Ik6ZbAUm26krqq91xsdEnZvXRczRoJbgC4m6JpnovUu/Yy+V4RCpEaTM/OtRKN/NPEWMvB6eRnYYPWQ4Y="
addons:
  coverity_scan:
    project:
      name: "Lnossa/testCI"
      description: "Test CI"
    notification_email: liviunossa@gmail.com
    build_command: "chmod ugo+x build.sh && ./build.sh"
    branch_pattern: master

#**************COVERITY END**************

script: chmod ugo+x build.sh && ./build.sh